### ISSUE TITLE
Verify Microsoft Edge support

### ISSUE THREAD

**Issue by aeksco** [aeksco/react-typescript-web-extension-starter#7]
[Microsoft Edge](https://www.microsoft.com/en-us/edge) should probably work out of the box since it's Chromium based, but we should make sure that it's officially supported.

**Comment by AlexRAV** [comment]
Old Microsoft Edge:
While attempting to setup extension, browser requires "author" field in the manifest.
After I've set "author" field, extension successfully installed, but popup doesn't opens. Here is popup console error:
![image](https://user-images.githubusercontent.com/13298791/79122208-56676c00-7dc1-11ea-84ec-37e6756722e9.png)

Versions: 
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

I think it's because of "chrome" object differs from the same object in Chrome Browser.

But in the new chrome-based Edge(Version 80.0.361.111 (Official build) (64-bit)) it works.

![edge](https://user-images.githubusercontent.com/13298791/79123126-a34c4200-7dc3-11ea-99e9-58df5f681ad2.gif)

**Comment by aeksco** [comment]
@AlexRAV Thanks for testing - really appreciate the .gif you included for clarity :fire:

Going to keep this ticket open as a reminder to myself to add notes for Edge to `README.md` - it's totally okay if it only works in the latest version of Edge - thanks again for testing both versions :+1:
